
FROM nginx:latest


RUN rm -rf /usr/share/nginx/html/*

COPY  /dist /usr/share/nginx/html


RUN rm -rf /etc/nginx/conf.d/default.conf
COPY default.conf /etc/nginx/conf.d/default.conf


RUN chmod -R 755 /u,sr/share/nginx/html


RUN chown -R 1000:1000 /opt/certificates  # Match Docker user UID
RUN  chmod -R 755 /opt/certificates

