FROM nginx:latest


RUN rm -rf /usr/share/nginx/html/*

COPY  /dist /usr/share/nginx/html


RUN rm -rf /etc/nginx/conf.d/default.conf
COPY default.conf /etc/nginx/conf.d/default.conf


RUN chmod -R 755 /usr/share/nginx/html

RUN mkdir -p /usr/share/nginx/html/certificates && \
    chown -R nginx:nginx /usr/share/nginx/html/certificates && \
    chmod -R 755 /usr/share/nginx/html/certificates

